### ISSUE TITLE
How are the coordinates of the points in the image  transformed through deformable transformation？　

### ISSUE THREAD

**Issue by h1310321230** [iwyoo/DIRNet-tensorflow#3]
I do not  know how the coordinates of the points in the moved image are changed after deformable transformation. Could you give me some help? If I want to get the coordinates of the points after deformable transformation, how to implement it ?

**Comment by iwyoo** [comment]
You can see the output tensor 'self.v'. (the vector for deformation)
https://github.com/iwyoo/DIRNet-tensorflow/blob/master/models.py#L54
You can use 'sess' to get numpy array like this line. 
https://github.com/iwyoo/DIRNet-tensorflow/blob/master/models.py#L77
And, you can also find a tensor of bicubifc interpolated vector here. 
https://github.com/iwyoo/DIRNet-tensorflow/blob/master/WarpST.py#L124
