### ISSUE TITLE
How to visualize the displacement vector ﬁeld?

### ISSUE THREAD

**Issue by h1310321230** [iwyoo/DIRNet-tensorflow#6]
Given a pair of images, the convolutional neural network outputs a displacement vector ﬁeld(DVF). The DVF is  a numpy array with two channels. If I want to visualize  it, what should I do ？Opencv and matplotlib can not do this . Can you help me? Thanks very much.

**Comment by iwyoo** [comment]
Color visualization is not related with this repository. Of course, you can suggest to expand the repository, but there are many implementation to visualize vector flow.
You can check this repo https://github.com/marximus/flowviz

**Comment by h1310321230** [comment]
It help me a lot. Thank you very much!
