### ISSUE TITLE
Error of annotation !

### ISSUE THREAD

**Issue by h1310321230** [iwyoo/DIRNet-tensorflow#8]
https://github.com/iwyoo/DIRNet-tensorflow/blob/0f8b4036737b743381da882ed075adbdcce1c7fb/WarpST.py#L123
this line is incorrect, the coordinate of the regular grid (x, y) are transformed into (x+v_x, y+v_y), where (v_x, v_y) are the displacement vector of the deformable field that is interpolated by bicubic interpolation. Is there any mistake in my understanding?

**Comment by iwyoo** [comment]
That (x, y) is source grid position. (```grid```)

**Comment by iwyoo** [comment]
That (x, y) is the ```grid``` position. 
As you say, (vx, vy) is the displacement vector. So (x+vx, y+vy) is  **source**  position.
There is typo, and I'll change it. Thanks!
