### ISSUE TITLE
What is the maximum input image size?

### ISSUE THREAD

**Issue by wakanawakana** [iwyoo/DIRNet-tensorflow#9]
Hello contributors.

I tried it.
It seems that it works well with the same 28 x 28 image as MNIST.
However, black pixels are displayed in the periphery.
After that, I tried to input an image of about 256 x 256, but the image was failing.
Since this network had only 4 convolution layers, I thought it was not dependent on image size, but that did not work.
Is this the limit of the model? I do not know whether it is a problem of post processing.
Is it possible to input large images?

```
import tensorflow as tf
from models import DIRNet
from config import get_config
from ops import mkdir
import cv2
import numpy as np

def main():
    sess = tf.Session()
    img_gray_x = np.array(cv2.imread('frame_000000.png', cv2.IMREAD_GRAYSCALE)) / 255.0
    img_gray_y = np.array(cv2.imread('frame_000001.png', cv2.IMREAD_GRAYSCALE)) / 255.0
    batch_x = img_gray_x[np.newaxis, 500:756, 1000:1256,np.newaxis]
    batch_y = img_gray_y[np.newaxis, 500:756, 1000:1256,np.newaxis]

    config = get_config(is_train=False)
    config.im_size = [256, 256]
    config.batch_size = 1

    mkdir(config.result_dir)

    reg = DIRNet(sess, config, "DIRNet", is_train=False)
    reg.restore(config.ckpt_dir)

    result_i_dir = config.result_dir+"/img"
    mkdir(result_i_dir)

    reg.deploy(result_i_dir, batch_x, batch_y)

if __name__ == "__main__":
    main()
```

**Comment by iwyoo** [comment]
Hello,
Please specify the error message you get. The main components of this implementation are not constrained on its image size (usually). I need to know main reason why the problem is caused in your case.

**Comment by wakanawakana** [comment]
Hi iwyoo.
Thank you for your reply.

The explanation was bad.
It is not a failure caused by an error.
The output image is distorted.

Did I use it without training?
Is this a problem with STNs((spatial transformer network)?

Distorted output at 256 x 256 input
![04_z](https://user-images.githubusercontent.com/24972079/51157997-b4a75580-18c5-11e9-9ff8-005589fdc56f.png) Z

**Comment by iwyoo** [comment]
Have you trained it before you deploy? I think the model is not trained well on your data.

**Comment by wakanawakana** [comment]
Thank you for your reply.
Is it impossible to process images of different sizes without training?

**Comment by iwyoo** [comment]
With this implementation and trained model checkpoint, the size can be different only if you use same scale of mnist characters and source and target images are positionally aligned. However, it you want to apply it to another domain, you need to train the model for your dataset domain.

**Comment by wakanawakana** [comment]
Thank you.
I learned to apply it to CT images in the paper.
Was this example different learning results?

"End-to-End Unsupervised Deformable Image Registration with a Convolutional Neural Network"
https://arxiv.org/abs/1704.06065

**Comment by iwyoo** [comment]
I haven't tested CT image experiments. (I only applied it to MNIST numbers). The checkpoint is not trained on CT images, so you need to train on that data.

**Comment by wakanawakana** [comment]
Thank you very much.

I understand.
I will learn my data and try it out.
